#!/usr/bin/env bash
# Builds the two generated artifacts:
#   1. resume-overhaul/stages/*.md — copies of the four specialist skills, so
#      the overhaul runs standalone with no sibling skills installed
#   2. dist/*.skill — the zips browser users upload to claude.ai
# The four specialist SKILL.md files are the single source of truth. Never edit
# stages/*.md by hand; edit the skill and re-run this. ./check.sh enforces it.
set -euo pipefail
cd "$(dirname "$0")"

SKILLS=plugins/shortlist/skills
STAGES=$SKILLS/resume-overhaul/stages
SPECIALISTS=(resume-diagnoser resume-recruiter resume-rewriter resume-hiring-manager)

echo "Generating stage files..."
rm -rf "$STAGES"
mkdir -p "$STAGES"
for s in "${SPECIALISTS[@]}"; do
  # Drop the YAML frontmatter: these are stage instructions inside another
  # skill, not skills in their own right, and five competing `name:` blocks in
  # one bundle would be ambiguous.
  awk 'BEGIN{fm=0} /^---$/ && fm<2 {fm++; next} fm>=2{print}' "$SKILLS/$s/SKILL.md" > "$STAGES/$s.md"
  if [ ! -s "$STAGES/$s.md" ]; then
    echo "FATAL: extracted nothing from $SKILLS/$s/SKILL.md — is the frontmatter malformed?" >&2
    exit 1
  fi
  echo "  $STAGES/$s.md"
done

echo "Generating single-file editions..."
# For ChatGPT Custom GPTs and Gemini Gems. Neither has a filesystem, so the
# overhaul's stages/ references are rewritten and the stage text is appended
# inline. Both products cap their instruction box well below the size of these
# files (8,000 chars for a Custom GPT, ~4,000 for a Gem), so they are meant to
# be uploaded as Knowledge, not pasted. See README.
SINGLE=dist/single-file
rm -rf "$SINGLE"
mkdir -p "$SINGLE"
for s in "${SPECIALISTS[@]}"; do
  cp "$STAGES/$s.md" "$SINGLE/$s.md"
  echo "  $SINGLE/$s.md"
done
{
  echo "<!-- shortlist single-file edition — generated by build.sh, do not edit by hand -->"
  echo
  # Drop frontmatter, drop the filesystem-only blocks, promote the singlefile
  # replacements out of their comments, and rewrite the table's stage paths.
  # The bundled/singlefile markers are an explicit contract in SKILL.md, not a
  # guess at its prose.
  awk 'BEGIN{fm=0} /^---$/ && fm<2 {fm++; next} fm>=2{print}' "$SKILLS/resume-overhaul/SKILL.md" \
    | awk '/<!-- bundled:begin -->/{skip=1; next} /<!-- bundled:end -->/{skip=0; next} !skip' \
    | sed -E 's|^<!-- singlefile: (.*) -->$|\1|' \
    | sed -E 's|`stages/([a-z-]+)\.md`|the **\1** section below|g'
  for s in "${SPECIALISTS[@]}"; do
    printf '\n---\n\n# Stage instructions: %s\n\n' "$s"
    cat "$STAGES/$s.md"
  done
} > "$SINGLE/resume-overhaul.md"
if grep -q "stages/" "$SINGLE/resume-overhaul.md"; then
  echo "FATAL: single-file overhaul still contains stages/ paths — the rewrite missed a reference" >&2
  exit 1
fi
echo "  $SINGLE/resume-overhaul.md"

echo "Packing dist/..."
# Only the zips — dist/single-file was just generated above and must survive.
mkdir -p dist
rm -f dist/*.skill
for d in "$SKILLS"/*/; do
  n=$(basename "$d")
  ( cd "$SKILLS" && zip -q -X -r "../../../dist/$n.skill" "$n" )
  echo "  dist/$n.skill"
done

echo "Done. Run ./check.sh to verify."
